### PR TITLE
Update to 4.14

### PR DESCRIPTION
**Pull request by andrijapanicsb**
Hi @pdion891 
I've added from 4.11 to 4.14
I have also moved the older docs to "before-4.11"
I have also "changed" the naming scheme to i.e. "4.11" vs. previously used "4.11.0" - for easier automation (please see the updated Readme file for detailed explanation)

Kindly see if this makes sense to you and let me know if that's OK.

### CODE REVIEW

**Comment by pdion891** [comment]
LGTM, 
Let me know if this PR is still a work in progress and I'll merge it when complete.

Thanks !

**Comment by andrijapanicsb** [comment]
Let me update with 4.14 files, in few days (hopefully) and then it will no more be WIP :)

Thanks

**Comment by andrijapanicsb** [comment]
@pdion891 I think this is now final, ready for merge - thx

**Comment by andrijapanicsb** [comment]
@pdion891, since I have also updated the code (forked one...) of Will's repo https://github.com/swill/generate_acs_rn - would it make any sense (or not) to actually "merge" his code to this repo of yours?

Reason for asking is, to:
1) have everything in the same place
2) not sure how "active" Will is and if he is ok with this or not. @swill?

Or we can leave it as it is (2 repos) - and I will be sending out PR to update Will's repo (no more JIRA, formating, updated config.json format, etc - in line with 4.11+ releases/behaviour).

thx

**Comment by pdion891** [comment]
I don't see any issue, in fact we should have a tool to generate RN for sure, it used to be a lot of manual steps to get a proper release notes, must be still be the same.

but unless I'm mistaking, we don't use jira anymore so this script must be quite outdated?

**Comment by andrijapanicsb** [comment]
Actually, I've sent the PR to Will's repo for that script - with updated versions that doesn't loop through the JIRA and a few more improvements/options - which we used internally for 4.11+ and it works well.

As for your scripts - we have also (internally) automated the commands/API docs build and it gets exported to web server where we consume it, etc.

I actually was wondering, does it make any sense to donate these 2 scripts to the Project, as I believe Will's script is already Apache 2.0 licenced (i.e. to keep them both in the /tools/ folder in source code of ACS) - optional, but worth considering.

Thx!

**Comment by pdion891** [comment]
I have no issue on moving this tool to the main project.  would kind of make sense to have it in the doc related repo if this current tool is useful enough.

**Comment by swill** [comment]
Hey @andrijapanicsb,
Thanks for the work on this.  Yes, I have not been super active recently as I have been very busy with the day job.  I have merged your changes in my repo (https://github.com/swill/generate_acs_rn)

I like the idea of moving those repos more formally into the cloudstack project.  I think the only reason @pdion891 and I have them in our own repos is because the two of us were doing a lot of the release notes back in the day and we developed helper code to support the process.

I am happy to move the repo to a new location.  Where would be the right place to move it to?  I will coordinate with whoever I need to in order to get it moved to the right place. 

Cheers...

**Comment by andrijapanicsb** [comment]
Thx Will - I really appreciate it - I will work on moving it to ACS repo - and will ping you once we are fully done - for the sake of feedback (and if you and Pier-Luc want to dismantle your repos).

Thanks again!

**Comment by swill** [comment]
Ok.  I can just "move" the repo to a location within the "apache" project
as well.  That will likely be simplest...

**Pull request merged**
